config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users
  resources :wallets
  resources :songs

  root 'home#show'

end

app/models/song.rb
class Song < ActiveRecord::Base
	belongs_to :user
	belongs_to :wallet

	# validates :wallet_id, presence: true, on: :create
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :username
  has_many :wallets
  has_many :songs

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:soundcloud]

   def self.from_omniauth(auth)
     where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     		user.email = 'blank@example.com'
      	user.provider = auth.provider
      	user.uid = auth.uid
      	user.username = auth.info.nickname
        user.image = auth.info.image
        user.following_count = auth.extra.raw_info.followings_count
        user.followers_count = auth.extra.raw_info.followers_count
      	user.password = Devise.friendly_token[0,20]
     end
  end

 # def self.find_first_by_auth_conditions(warden_conditions)
 #  conditions = warden_conditions.dup
 #  if username = conditions.delete(:username)
 #    where(conditions).where(["lower(username) = :value", { value: username.downcase }]).first
 #  else
 #    where(conditions).first
 #  end
 # end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.soundcloud_data"] && session["devise.soundcloud_data"]["extra"]["raw_info"]
        user.username = data["username"] if user.username.blank?
      end
    end
  end

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
	belongs_to :user
	has_many :songs

	validates :name, presence: true, on: :create

  # scope :filtered, -> { where(checked: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def show
		@song = Song.new
		@wallets = Wallet.all

		client = Soundcloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'],
                        client_secret: ENV['SOUNDCLOUD_SECRET'])
		@songs = client.get('/tracks', limit: 5, order: 'hotness')
	end
	
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	before_action :set_song, only: [:show, :edit, :update, :destroy]

	def index
		keyword = params[:q]
		@song = Song.new
		# @song_ids = []
		@wallets = Wallet.all

		client = Soundcloud.new(client_id: ENV['SOUNDCLOUD_CLIENT_ID'],
                        client_secret: ENV['SOUNDCLOUD_SECRET'])
		
		unless keyword.nil?
			@songs = client.get('/tracks', q: keyword, limit: 10)
			# @song_ids = @songs.map(&:id)
		else
			@songs = []
		end

	end

	def show
	end

	def create
		@song = Song.create(song_params)
		redirect_to :back 
	end

	def destroy
		@song.destroy
		redirect_to :back
	end

	private

		def set_song
			@song = Song.find(params[:id])
		end

		def song_params
			params.require(:song).permit(:name, :user_id, :wallet_id, :track_id)
		end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]
  def soundcloud
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.sign_in_count
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Soundcloud") if is_navigational_format?
    else
      session["devise.soundcloud_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
	 	@users = User.all
	 	@wallets = Wallet.all
    @filtered = Wallet.where('name IN (?)', params[:names])
    @h = Hash.new(0)
	end

end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
	before_action :set_wallet, only: [:show, :edit, :update, :destroy]


	def index
		@wallets = Wallet.all
	end

	def show
		@songs = @wallet.songs
	end

	def new
		@wallet = Wallet.new
	end

	def create
		@wallet = Wallet.create(wallet_params)
		if @wallet.save
			redirect_to wallets_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		@wallet.update(wallet_params)
		if @wallet.update(wallet_params)
			redirect_to wallet_path(@wallet)
		else
			render :edit
		end
	end

	def destroy
			@wallet.destroy
			redirect_to :back 
	end

	private

		def set_wallet
			@wallet = Wallet.find(params[:id])
		end

		def wallet_params
			params.require(:wallet).permit(:name, :checked).merge(user_id: current_user.id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/show.html.erb
	<% if user_signed_in? %>
		<section class="content">
			<iframe allowtransparency="true" scrolling="no" frameborder="no" src="https://w.soundcloud.com/icon/?url=http%3A%2F%2Fsoundcloud.com%2F<%= current_user.username %>&color=black_white&size=48" style="width: 48px; height: 48px;"></iframe>
			<strong><p>Signed in as <%= current_user.username %></p></strong>
					
				<h2 class="head">Top 5 Tracks</h2>
				<hr>
				<% @songs.each do |song| %>
		  				<iframe width="100%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.	com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= song.id %>&show_artwork=tru&client_id=ENV[SOUNDCLOUD_CLIENT_ID]"></iframe>
					<br>
					<%= form_for @song do |f| %>
		  			<% @wallets.each do |wallet| %>
							<% if current_user.id == wallet.user_id %>
								<%= f.hidden_field :track_id, value: song.id %>
								<%= f.radio_button :wallet_id, wallet.id %>
								<%= f.label wallet.name %>
							<% end %>
						<% end %>
						<% unless current_user.wallets.empty? %>
							<%= f.submit 'Add', class: 'actions' %>
						<% end %>
					<% end %>
		  			<hr>
				<% end %>
			</section>
	<% else %>
			<%= image_tag "home.png", class: 'home-image' %>
			<h2 id="welcome">Welcome to MusicWallet</h2><br>
			<div id="exp">The Address for Quality Sounds<br><br><br>Powered by Soundcloud</div>
			<div id="connect"><%= link_to "Connect with Soundcloud", user_omniauth_authorize_path(:soundcloud), class: 'actions' %></div>
	<% end %>

app/views/layouts/_nav.html.erb
<header>
		<nav>
      <span class="navi">MusicWallet</span>	
			<span><%= link_to 'Home', root_path, class: 'navi' %></span>
			<span><%= link_to 'Users', users_path, class: 'navi' %></span>
			<span><%= link_to 'Search', songs_path, class: 'navi' %></span>
			<span><%= link_to 'Wallets', wallets_path, class: 'navi' %></span>
			<span><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navi' %></span>
		</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicWallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<% if user_signed_in? %>
		<%= render 'layouts/nav' %>
	<% end %>
<%= yield %>

</body>
</html>

app/views/songs/index.html.erb
<section class="content">
		<%= form_tag '/songs', method: "get" do %>
			<%= text_field_tag(:q) %>
			<%= submit_tag 'Search', class: 'actions' %>
		<% end %>
		<hr>
		<% @songs.each do |song| %>

			<iframe width="100%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.	com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= song.id %>&show_artwork=tru&client_id=ENV[SOUNDCLOUD_CLIENT_ID]"></iframe>
			<br>
			<%= form_for @song do |f| %>
		  	<% @wallets.each do |wallet| %>
					<% if current_user.id == wallet.user_id %>
						<%= f.hidden_field :track_id, value: song.id %>
						<%= f.radio_button :wallet_id, wallet.id %>
						<%= f.label wallet.name %>
					<% end %>
				<% end %>
				<% unless current_user.wallets.empty? %>
					<%= f.submit 'Add', class: 'actions' %>
				<% end %>
			<% end %>
			<hr>
		<% end %>
</section>

app/views/users/index.html.erb
<section class="content">

    <%= form_tag '/users', method: "get" do %>
      <% @wallets.each do |wallet| %>

        <% if @h[wallet.name] < 1 %>

          <% @h[wallet.name] += 1 %>
          <%= check_box_tag 'names[]', wallet.name %>
          <%= label_tag wallet.name %>

        <% end %>

      <% end %>

      <%= submit_tag 'Filter', class: 'actions' %>
    <% end %>
    <hr>
    <% @users.each do |user| %>

      <% unless user.id == current_user.id %>

        <% if @filtered.all? { |x| user.wallets.include?(x) } %>

          <span class="users">
            <div><%= image_tag user.image %></div>
            <div><strong><%= user.username %></strong></div>
            <br>
            <div><strong>Followers: </strong> <%= user.following_count %></div>
            <br>
            <div><strong>Following: </strong> <%= user.followers_count %></div>
            <p><strong>Wallets</strong></p>

            <% @wallets.each do |wallet| %>
              <% if user.id == wallet.user_id %>
                <div><%= link_to wallet.name, wallet_path(wallet) %></div>
                <br>
              <% end %>

            <% end %>

          </span>
        <% end %>

      <% end %>

    <% end %>
</section>

app/views/wallets/_form.html.erb
<div class='form'>
	<%= form_for @wallet do |f| %>
  <h2>Add Wallet</h2>
	 <% if @wallet.errors.any? %>
    			<div class="error_explanation">
      			<h2><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      			<ul>
     					<% @wallet.errors.full_messages.each do |message| %>
        				<li><%= message %></li>
      				<% end %>
     				 </ul>
    			</div>
  	<% end %>
    <br>
		<%= f.hidden_field :user_id %>
		<%= f.label :name, 'Wallet Name:' %>
    <br><br>
		<%= f.text_field :name, size: '50' %>
    <br><br>
		<%= f.submit 'Add', class: 'actions' %>
	<% end %>
</div>

app/views/wallets/edit.html.erb
<%= render 'form' %>

app/views/wallets/index.html.erb
<section class="content">	
	<h1 style="text-align:center;">Wallets</h1>
		<div id="wlist">
			<% @wallets.each do |wallet| %>
				<% if wallet.user_id == current_user.id %>
					<h2 class="head"><%= link_to wallet.name, wallet_path(wallet), class: 'wallets' %></h2>
					<%= link_to 'Edit', edit_wallet_path(wallet), class: 'actions' %>
					<%= link_to 'Remove Wallet', wallet_path(wallet), method: :delete, class: 'actions' %>
				<% end %>
			<% end %>
			<br><br>
			<div style="text-align:center;"><%= link_to 'Add Wallet', new_wallet_path, class: 'actions' %></div>
		</div>
</section>

app/views/wallets/new.html.erb
<%= render 'form' %>

app/views/wallets/show.html.erb
<section class="content">
	<h1><%= @wallet.name %></h1>
	<div><strong>User:</strong> <%= @wallet.user.username %></div>
	<br>
	<% @songs.each do |song| %>
		<% if song.wallet_id == @wallet.id %>
			<iframe width="100%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.	com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F<%= song.track_id %>&show_artwork=tru&client_id=ENV[SOUNDCLOUD_CLIENT_ID]"></iframe>
			<br><br>
			<% if @wallet.user_id == current_user.id %>
				<%= button_to 'Remove', song, method: :delete, class: 'actions' %>
			<% end %>
			<hr>
		<% end %>
	<% end %>
</section>